// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTCoEwns-wOPr90TgstXjV4oCDmV4edc',
    appId: '1:798131773001:web:9d8aae7ecfd8cd561ee998',
    messagingSenderId: '798131773001',
    projectId: 'mapapp-877e3',
    authDomain: 'mapapp-877e3.firebaseapp.com',
    storageBucket: 'mapapp-877e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqBu3FUN5Gxvl-wB8lS07WbE2R-TuYTE',
    appId: '1:798131773001:android:fa49ffab116c6ea31ee998',
    messagingSenderId: '798131773001',
    projectId: 'mapapp-877e3',
    storageBucket: 'mapapp-877e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAurFp8hUnn5Ja5v19cYlqvC7AAl1mvg9w',
    appId: '1:798131773001:ios:c3b4e2d7b7f1873c1ee998',
    messagingSenderId: '798131773001',
    projectId: 'mapapp-877e3',
    storageBucket: 'mapapp-877e3.appspot.com',
    iosBundleId: 'com.example.mapapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAurFp8hUnn5Ja5v19cYlqvC7AAl1mvg9w',
    appId: '1:798131773001:ios:609c46e77ec1da6b1ee998',
    messagingSenderId: '798131773001',
    projectId: 'mapapp-877e3',
    storageBucket: 'mapapp-877e3.appspot.com',
    iosBundleId: 'com.example.mapapp.RunnerTests',
  );
}
